### ISSUE TITLE
Springフレームワークを用いてjspにリストボックスを生成する仕方がわかりません

### ISSUE THREAD

**Issue by milmilmi** [milmilmi/test#1]
掲題の通りです
[これ](
http://arakan-pgm-ai.hatenablog.com/entry/2017/03/18/230802)を試したらうまくいくかと思ったのですがContoroller外のクラスに存在するListをもってくる方法が分かりません。

**Comment by milmilmi** [comment]
[これ](http://stroll.hatenablog.com/entry/2015/08/30/212406)を参考にしたらどうにかなる…？かも？
課題はItem型のインスタンスを生成してArrayListに格納してる

**Comment by milmilmi** [comment]
path = "name"じゃダメみたい

> サーブレット jsp のServlet.service()が例外を投げました [月 9 04 14:35:47 JST 2017]
> 重大: Servlet.service() for servlet [appServlet] in context with path [/sales] threw exception [An exception occurred processing JSP page /WEB-INF/views/init.jsp at line 28
> 
> 25: <form:form modelAttribute="SalesForm" action="meisaiadd">
> 26:     <div>
> 27:         <span class="itemName">商品：</span>
> 28:         <form:select path="name" items="${ItemList}"/>
> 29:     </div>
> 30:     <div>
> 31:         <span class="amount">点数：</span>
> 
> 
> Stacktrace:] with root cause [月 9 04 14:35:47 JST 2017]

**Comment by milmilmi** [comment]
![image](https://user-images.githubusercontent.com/18700030/30016695-260405c4-9191-11e7-98c9-f46c19fcad82.png)
listのメモリアドレスは取れてきてるっぽいわね
getName()で何とかなるかと思ったけどならなかった…

**Comment by KeishiroOsaki** [comment]
いま、コードを確認しましたが、init.jspが元に戻っていませんか？

**Comment by milmilmi** [comment]
@KeishiroOsaki 戻しました。
```
<span class="itemName">商品：</span>
<form:form modelAttribute="salesForm" action="/start">
<form:select path = "name" items="${ItemList}"/>
</form:form>
```
modelAttribute="SalesForm"にしてたけどsを小文字にしたら解決したので。（なぜかはわかりません）

**Comment by KeishiroOsaki** [comment]
>課題はItem型のインスタンスを生成してArrayListに格納してる
これは、商品を明細に追加するときの挙動だと思います。

**Comment by milmilmi** [comment]
@KeishiroOsaki 
今コミットしてるRecordManager.javaと、SalesContoroller.javaを見てもらえますか。名前だけ取りたいっていうやつです:sob:

**Comment by KeishiroOsaki** [comment]
`//String itemname = RecordManager.getItemList();　ここらへんで名前を直接取ろうとしたら怒られた

例外が起きた原因は、getItemList()メソッドの返り値の型がString型ではないから、itemnameには代入できなかったことによるものだと思われます。

改善策については、ちょっとコードを書き換えてみますので、そちらでご確認ください。

**Comment by milmilmi** [comment]
お陰様で名前取れました。ありがとうございます。
ここのところ、initとaddで共有してるから他の名前で持っといた方がいいかもですね・

**Comment by milmilmi** [comment]
お陰様で名前取れました。ありがとうございます。
ここのところ、initとaddで共有してるから他の名前で持っといた方がいいかもですね
こちらcloseします。
